### ISSUE TITLE
When I refresh the page, I log out

### ISSUE THREAD

**Issue by dislazy** [alyssaxuu/mapus#4]
When I refresh the page, I log out, which feels that the experience is not very good

**Comment by alyssaxuu** [comment]
Hmm, this could be due to [this](https://github.com/alyssaxuu/mapus/blob/c71927c64534c5971989aec8244175012eefe1ef/src/main.js#L67). I noticed there seems to be some inconsistencies where sometimes it will keep you logged in on refresh, and sometimes not. It appears it could have something to do with a [delay when loading firebase](https://stackoverflow.com/questions/57383582/firebase-listen-to-when-auth-loading-has-completed), it might check when it's not ready yet. You could try increasing the timeout there to see if it works. Ultimately I'm not sure what the fix would be, I'd have to look into it further.

**Comment by dislazy** [comment]
> Hmm, this could be due to [this](https://github.com/alyssaxuu/mapus/blob/c71927c64534c5971989aec8244175012eefe1ef/src/main.js#L67). I noticed there seems to be some inconsistencies where sometimes it will keep you logged in on refresh, and sometimes not. It appears it could have something to do with a [delay when loading firebase](https://stackoverflow.com/questions/57383582/firebase-listen-to-when-auth-loading-has-completed), it might check when it's not ready yet. You could try increasing the timeout there to see if it works. Ultimately I'm not sure what the fix would be, I'd have to look into it further.

Okay, thank you very much, I wonder if it is possible to store the session in localstorage

**Comment by 403-Fruit** [comment]
I think this is caused by [this line](https://github.com/alyssaxuu/mapus/blob/c71927c64534c5971989aec8244175012eefe1ef/src/main.js#L888):  

```javascript
// Make sure the session persists after closing the window so the user doesn't have to log in every time
firebase.auth().setPersistence(firebase.auth.Auth.Persistence.SESSION)
```  

In the [firebase docs](https://firebase.google.com/docs/auth/web/auth-state-persistence#supported_types_of_auth_state_persistence), `firebase.auth.Auth.Persistence.SESSION` is described as  

> Indicates that the state will only persist in the current session or tab, and will be cleared when the tab or window in which the user authenticated is closed  

I think `firebase.auth.Auth.Persistence.LOCAL` is the right setting:  

>Indicates that the state will be persisted even when the browser window is closed or the activity is destroyed in React Native. An explicit sign out is needed to clear that state. Note that Firebase Auth web sessions are single host origin and will be persisted for a single domain only  

I've created a pull request with this change here: https://github.com/alyssaxuu/mapus/pull/5
